easyboot:
  database:
    type: mysql
    url: jdbc:mysql://rm-2ze8v9g2o013w44f8wo.mysql.rds.aliyuncs.com:3306/easy-boot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&connectTimeout=1000&rewriteBatchedStatements=true
    username: weiwan
    password: weiwan=123
    schema: easy-boot
    hikari:
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 3
      validation-timeout: 3000
  file:
    local:
      directory: '@local.upload.directory@'
    store-type: local
    url-prefix: http://127.0.0.1:3001/static

  multi-tenant:
    enable: false

spring:
  redis:
    client-name: weiwan
    host: r-2ze8uv05uw7q54fe75pd.redis.rds.aliyuncs.com
    password: weiwan=123
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB